# Generated by Django 3.1.1 on 2020-10-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.TextField(max_length=2000, null=True)),
                ('image', models.ImageField(null=True, upload_to='categories/category1/')),
                ('icon', models.TextField(max_length=2000, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.TextField(max_length=2000, null=True)),
                ('image', models.ImageField(null=True, upload_to='categories/category2/')),
                ('icon', models.TextField(max_length=2000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category1')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.TextField(max_length=2000, null=True)),
                ('image', models.ImageField(null=True, upload_to='categories/category3/')),
                ('icon', models.TextField(max_length=2000, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
