# Generated by Django 3.1.1 on 2020-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('cover', models.ImageField(null=True, upload_to='shop/')),
                ('logo', models.ImageField(null=True, upload_to='shop/')),
                ('phone', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
