# Generated by Django 3.1.1 on 2020-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
