# Generated by Django 3.1.1 on 2020-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(null=True, upload_to='shops/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(null=True, upload_to='shops/'),
        ),
    ]
