# Generated by Django 3.1.1 on 2020-10-10 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_shopusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopUsers',
            new_name='ShopUser',
        ),
    ]
